    <header class="header">
        <!-- Logo Section -->
        <div class="header-logo">
            <p>JOBS</p>
            <img src="styles/images/logo.png" alt="Logo Image">
            <p>IME</p>
        </div>
        
        <!-- Navigation Bar -->
        <nav class="nav-bar">
            <a href="index.php" class="nav-item">
                <p class="nav-main-item">Home</p>
                <p class="nav-sub-item">Main page</p>
            </a>
            <a href="about.php" class="nav-item">
                <p class="nav-main-item">About</p>
                <p class="nav-sub-item">More information</p>
            </a>
            <a href="jobs.php" class="nav-item">
                <p class="nav-main-item">Jobs</p>
                <p class="nav-sub-item">Find opportunities</p>
            </a>
            <a href="apply.php" class="nav-item">
                <p class="nav-main-item">Apply</p>
                <p class="nav-sub-item">Send applications</p>
            </a>
            <a href="enhancements.php" class="nav-item" id="last-item">
                <p class="nav-main-item">Enhancements</p>
                <p class="nav-sub-item">Feedback and Suggestions</p>
            </a>
        </nav>
    </header>